# Generated by Django 3.1.6 on 2021-02-12 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=200)),
                ('sold_price', models.IntegerField()),
                ('bids', models.IntegerField()),
                ('sold_date', models.CharField(max_length=20)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('card_link', models.URLField(blank=True, max_length=500)),
                ('image_link', models.URLField(blank=True, max_length=500)),
                ('image_upload', models.ImageField(upload_to=None)),
                ('card_data', models.JSONField(default=dict)),
            ],
        ),
    ]
