# Generated by Django 3.1.6 on 2021-02-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='bids',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='card_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='data',
            name='image_upload',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='data',
            name='player',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='sold_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='data',
            name='sold_price',
            field=models.IntegerField(blank=True),
        ),
    ]
