# Generated by Django 3.1.6 on 2021-02-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210212_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='card_data',
        ),
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
        migrations.RemoveField(
            model_name='data',
            name='image_upload',
        ),
    ]
